language: go
services:
- docker
go:
- 1.8
install:
- go get gopkg.in/alecthomas/gometalinter.v1
- gometalinter.v1 --install
before_script:
- pwd
- gometalinter.v1 --vendor --deadline=300s --disable=gotype --disable=gocyclo ./...
script:
- make build
notifications:
  slack:
    secure: GSy8ZrwofrubjK+2baXWSB8HmRwtMw3zR6g9QvPIpdYLxSKjCH5DjalwEOqP9qD4btczMO5VYJOUEs+gTc9AybipJFPevL9qVFqhbtuW0BLzmm3gCfrpHoF+pB5mjSfNMQP0Sl1tIhb3A9wRJtpDnQhG/1E3nU1C9X1dEwxUkG25H8XJNxm3U6/6sGvWCaG5AmA/u3hYjst63LgV6SZ23MgEYfQqMrVo7ZBnLotXWDUA1ZyW3j46F4maHEVI1ThhleFrUVOuxq/xlGDryRLs20h2juhaAvmu8GYH+yF0WyoQ8RDbbDC3OsHCweCD/AxksjETt0Ej2oiK3gOHjkVrsSpG9jicWL0uUiH2QHdClOn//xvZzZNhty6EjfLQclXPFpfTGnfpBzZcp+sxyjwCrVHaeV9dG7vagflK+dzCFTVAG85U0n2hZmJ2HSOT4RcvOWEMQYef+azskt3CkYLoBG/wSV5jZYbPsUM6WguFW9B9mhos+Mpg+xN8BeGzKop8qYF6RnXWQN22m6ZdiSj1GHrpjZwYj3sII92QJsawSCGtao9mP9igvBEdLwcDrJVehfyfhukaEb2HL7mzkqZmf7HTe7w9U58Dd2Un0plmDPscPz0l1UZw4b6eRLlu895gOIav5+9KIVFPB1ArjNJ7BI2IK8E/GO8LfB3/YrHO+j8=
