language: go

services:
  - docker

go:
  - 1.8

install:
  - go get gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

before_script:
  - gometalinter.v1 --disable-all --enable=goimports --enable=gofmt ./...

script:
  - make build || exit 1
